config/routes.rb
Rails.application.routes.draw do
  devise_for :sign_ups
  resources :projects
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/sign_up.rb
class SignUp < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_sign_up!

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Projeto criado com sucesso." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Projeto atualizado com sucesso." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Projeto deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:nome, :servico, :responsavel)
    end
end

app/controllers/sign_up/confirmations_controller.rb
# frozen_string_literal: true

class SignUp::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/sign_up/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class SignUp::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/sign_up/passwords_controller.rb
# frozen_string_literal: true

class SignUp::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/sign_up/registrations_controller.rb
# frozen_string_literal: true

class SignUp::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   #def create
    # super
   #end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
    def after_sign_up_path_for sign_up_session_path
   super sign_up_session_path
    'sign_up_session_path'
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/sign_up/sessions_controller.rb
# frozen_string_literal: true

class SignUp::SessionsController < Devise::SessionsController
   before_action :configure_sign_up_params, only: [:create]

   #GET /resource/sign_in
   #def new
    # super
   #end

   #POST /resource/sign_in
   #def create
    # super
   #end

   #DELETE /resource/sign_out
   #def destroy
    # super
   #end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/sign_up/unlocks_controller.rb
# frozen_string_literal: true

class SignUp::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def data_br(data_us)
        data_us.strftime("%d/%m/%Y")
    end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_do_projeto %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :servico_prestado %>
    <%= form.text_area :servico %>
  </div>

  <div class="field">
    <%= form.label :responsavel_pelo_projeto %>
    <%= form.text_area :responsavel %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editando informações:</h1>

<%= render 'form', project: @project %>

<%= link_to 'Mostrar', @project %> |
<%= link_to 'Voltar', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bem vindo á area de projetos, <%=current_sign_up.email%>.</h1>

<table>
  <thead>
    <tr>
      <th>Nome do projeto | </th>
      <th>Servico prestado | </th>
      <th>Responsavel pelo projeto | </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.nome %></td>
        <td><%= project.servico %></td>
        <td><%= project.responsavel %></td>
        <td><%= link_to 'Mostrar', project %></td>
        <td><%= link_to 'Editar', edit_project_path(project) %></td>
        <td><%= link_to 'Deletar', project, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p>
Para criar um novo projeto, clique no link abaixo: 
</p>

<li>
<%= link_to 'Novo projeto.', new_project_path %>
</li>

<% if sign_up_signed_in? == true %>

<p> Para se desconectar, clique em "Logoff" logo abaixo:</p>
<li>
    <%= link_to "Logoff.", destroy_sign_up_session_path, method: :delete %>
</li>

<% end %>

app/views/projects/new.html.erb
<h1>Novo Projeto:</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome do projeto:</strong>
  <%= @project.nome %>
</p>

<p>
  <strong>Servico prestado:</strong>
  <%= @project.servico %>
</p>

<p>
  <strong>Responsavel pelo projeto:</strong>
  <%= @project.responsavel %>
</p>

<%= link_to 'Editar', edit_project_path(@project) %> |
<%= link_to 'Voltar', projects_path %>

app/views/sign_ups/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/sign_ups/shared/_links.html.erb
<%#<%- if controller_name != 'sessions' %>
  <%#<%= link_to "Log in", new_session_path(resource_name) %><br />
<%#<% end %>

<%#<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#<%= link_to "Registrar", new_registration_path(resource_name) %><br />
<%#<% end %>

<%#< <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <<%#%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
 <%#<% end %> 

<%#<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#<%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%#<% end %>

<%#<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#<%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<%#<% end %>

<%#<%- if devise_mapping.omniauthable? %>
  <%#<%- resource_class.omniauth_providers.each do |provider| %>
    <%#<%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <%#<% end %>
<%#<% end %>

app/views/welcome/index.html.erb
<% if sign_up_signed_in? == true %>

<h1>Bem vindo, <%= current_sign_up.email %>!</h1>
<p><strong>Data:</strong> <%= data_br(Date.today) %></p>

<p>
Para acessara a área de Controle dos projetos, clique no link abaixo: 
</p>
<li>
    <%= link_to "Área de Controle.", projects_path %>
</li>

<p> Para se desconectar, clique em "Logoff" logo abaixo:</p>
<li>
    <%= link_to "Logoff.", destroy_sign_up_session_path, method: :delete %>
</li>

<% else %>

<h1>Bem vindo, 
<p><strong>Data:</strong> <%= data_br(Date.today) %></p>

<p> 
Caso não tenha um cadastro, acesse "Novo Cadastro." logo abaixo:
</p>
<li>
    <%= link_to "Novo Cadastro.", new_sign_up_registration_path %>

<p>
Para acessar a área de login, clique no link abaixo:
</p>
<li>
    <%= link_to "Login.", new_sign_up_session_path %> 
</li>
<% end %>